### ISSUE TITLE
ID:36 Chevelle SS 454 Sport Coupé '70	is not shown in legend car dealer as of 11/13/2024

### ISSUE THREAD

**Issue by policeman0077** [ddm999/gt7info#9]
Car ID:36 
Chevelle SS 454 Sport Coupé '70	
is not shown in legend car dealer as of 11/13/2024
![image](https://github.com/user-attachments/assets/d23cd8f8-8379-4f47-9691-294f5113cbbb)
![image](https://github.com/user-attachments/assets/a60a27d1-2cc3-4080-a990-5a3bd8b18f73)

**Comment by ddm999** [comment]
This will just have been a one day issue:
PD sometimes manually add a car at around 08:00 UTC, but the site gets updated only at ~00:15 UTC each day.

Since this car specifically has shown up on the site after the day change, I'm going to close this as "kind of a known problem with no fix".
(I could adjust the update system to happen each day at 08:15 UTC, but then it'll be very incorrect for 8 hours instead of rarely slightly incorrect for 16 hours.)
